# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
before_install:
  - sudo apt-get install -y libv8-dev
addons:
  apt:
    update: true
language: R
sudo: false
cache: packages
